
class Account:
    def __init__(
        self, 
        id, 
        account_blocked, 
        buying_power,
        cash, 
        created_at, 
        currency, 
        daytrade_count,
        daytrading_buying_power,
        equity, 
        initial_margin,
        last_equity,
        last_maintence_margin,
        long_market_value,
        maintence_margin,
        multiplier,
        pattern_day_trader, 
        portfolio_value,
        regt_buying_power,
        short_market_value,
        sma,
        status,
        trade_suspended_by_user,
        trading_blocked,
        transfers_blocked
        ):

        self.id=id
        self.account_blocked=account_blocked
        self.buying_power=buying_power
        self.cash=cash
        self.created_at=created_at
        self.currency=currency
        self.daytrade_count=daytrade_count
        self.daytrading_buying_power=daytrading_buying_power
        self.equity=equity
        self.initial_margin=initial_margin
        self.last_equity=last_equity
        self.last_maintence_margin=last_maintence_margin
        self.long_market_value=long_market_value
        self.maintenance_margin=maintence_margin
        self.multiplier=multiplier
        self.pattern_day_trader=pattern_day_trader
        self.portfolio_value=portfolio_value
        self.regt_buying_power=regt_buying_power
        self.short_market_value=short_market_value
        self.sma=sma
        self.status=status
        self.trade_suspended_by_user=trade_suspended_by_user
        self.trading_blocked=trading_blocked
        self.transfers_blocked=transfers_blocked

class Order:
    def __init__(self, 
        id,
        client_order_id,
        created_at,
        updated_at,
        submitted_at,
        filled_at,
        expired_at,
        canceled_at,
        failed_at,
        replaced_at,
        replaced_by,
        replaces,
        asset_id,
        symbol,
        asset_class,
        notional,
        qty,
        filled_qty,
        filled_avg_price,
        order_class,
        order_type,
        type,
        side,
        time_in_force,
        limit_price,
        stop_price,
        status,
        extended_hours,
        legs,
        trail_percent,
        trail_price,
        hwm):

        
        self.id=id
        self.client_order_id=client_order_id
        self.created_at=created_at
        self.updated_at=updated_at
        self.submitted_at=submitted_at
        self.filled_at=filled_at
        self.expired_at=expired_at
        self.canceled_at=canceled_at
        self.failed_at=failed_at
        self.replaced_at=replaced_at
        self.replaced_by=replaced_by
        self.replaces=replaces
        self.asset_id=asset_id
        self.symbol=symbol
        self.asset_class=asset_class
        self.notional=notional
        self.qty=qty
        self.filled_qty=filled_qty
        self.filled_avg_price=filled_avg_price
        self.order_class=order_class
        self.order_type=order_type
        self.type=type
        self.side=side
        self.time_in_force=time_in_force
        self.limit_price=limit_price
        self.stop_price=stop_price
        self.status=status
        self.extended_hours=extended_hours
        self.legs=legs
        self.trail_percent=trail_percent
        self.trail_price=trail_price
        self.hwm=hwm

class Position:
    def __init__(self,  
        asset_id,
        symbol,
        exchange,
        asset_class, 
        avg_entry_price, 
        qty,
        qty_available,
        side,
        market_value,
        cost_basis,
        unrealized_pl,
        unrealized_plpc,
        unrealized_intraday_pl,
        unrealized_intraday_plpc,
        current_price,
        lastday_price,
        change_today
    ):

        self.asset_id=asset_id
        self.symbol=symbol
        self.exchange=exchange
        self.asset_class=asset_class
        self.avg_entry_price=avg_entry_price
        self.qty=qty
        self.qty_available=qty_available
        self.side=side
        self.market_value=market_value
        self.cost_basis=cost_basis
        self.unrealized_pl=unrealized_pl
        self.unrealized_plpc=unrealized_plpc
        self.unrealized_intraday_pl=unrealized_intraday_pl
        self.unrealized_intraday_plpc=unrealized_intraday_plpc
        self.current_price=current_price
        self.lastday_price=lastday_price
        self.change_today=change_today

class Asset:
    def __init__(self, 
        id, 
        asset_class,
        exchange, 
        symbol, 
        status, 
        tradable,
        marginable,
        shortable,
        easy_to_borrow,
        fractionable,
    ):
        self.id=id
        self.asset_class=asset_class
        self.exchange=exchange 
        self.symbol=symbol
        self.status=status
        self.tradable=tradable
        self.marginable=marginable
        self.shortable=shortable
        self.easy_to_borrow=easy_to_borrow
        self.fractionable=fractionable